library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity uart_core is
    Port (
        clk          : in  STD_LOGIC;
        reset        : in  STD_LOGIC;

        baud_div     : in  STD_LOGIC_VECTOR (15 downto 0);

        ----------------------------------------------------------------
        -- TX interface
        ----------------------------------------------------------------
        tx_data_in   : in  STD_LOGIC_VECTOR (7 downto 0);
        tx_write     : in  STD_LOGIC;
        tx_full      : out STD_LOGIC;
        tx_empty     : out STD_LOGIC;
        tx_busy      : out STD_LOGIC;

        ----------------------------------------------------------------
        -- RX interface
        ----------------------------------------------------------------
        rx_data_out  : out STD_LOGIC_VECTOR (7 downto 0);
        rx_read      : in  STD_LOGIC;
        rx_empty     : out STD_LOGIC;
        rx_full      : out STD_LOGIC;
        rx_valid     : out STD_LOGIC;
        frame_error  : out STD_LOGIC;

        ----------------------------------------------------------------
        -- UART pins
        ----------------------------------------------------------------
        tx           : out STD_LOGIC;
        rx           : in  STD_LOGIC
    );
end uart_core;


architecture Behavioral of uart_core is

    --------------------------------------------------------------------
    -- BAUD GENERATOR
    --------------------------------------------------------------------
    signal baud_tick : STD_LOGIC;


    --------------------------------------------------------------------
    -- TX FIFO
    --------------------------------------------------------------------
    signal tx_fifo_dout  : STD_LOGIC_VECTOR(7 downto 0);

    signal tx_fifo_rd_en : STD_LOGIC;

    signal tx_fifo_full  : STD_LOGIC;
    signal tx_fifo_empty : STD_LOGIC;


    --------------------------------------------------------------------
    -- UART TX
    --------------------------------------------------------------------
    signal uart_tx_data  : STD_LOGIC_VECTOR(7 downto 0);
    signal uart_tx_start : STD_LOGIC;
    signal uart_tx_busy  : STD_LOGIC;


    --------------------------------------------------------------------
    -- TX CONTROL FSM
    --------------------------------------------------------------------
    type tx_ctrl_state_t is
    (
        TX_IDLE,
        TX_READ_REQUEST,
        TX_WAIT_DATA,
        TX_START,
        TX_WAIT_BUSY,
        TX_WAIT_DONE
    );

    signal tx_ctrl_state : tx_ctrl_state_t := TX_IDLE;


    --------------------------------------------------------------------
    -- UART RX
    --------------------------------------------------------------------
    signal uart_rx_data      : STD_LOGIC_VECTOR(7 downto 0);
    signal uart_rx_valid     : STD_LOGIC;
    signal uart_rx_busy      : STD_LOGIC;
    signal uart_frame_error  : STD_LOGIC;


    --------------------------------------------------------------------
    -- RX FIFO
    --------------------------------------------------------------------
    signal rx_fifo_wr_en : STD_LOGIC;
    signal rx_fifo_rd_en : STD_LOGIC;

    signal rx_fifo_din   : STD_LOGIC_VECTOR(7 downto 0);
    signal rx_fifo_dout  : STD_LOGIC_VECTOR(7 downto 0);

    signal rx_fifo_full  : STD_LOGIC;
    signal rx_fifo_empty : STD_LOGIC;


    --------------------------------------------------------------------
    -- IMPORTANT RX DELAY SIGNAL
    --
    -- uart_rx_valid is generated by the UART receiver at a clock edge.
    -- We delay it by one clock before giving it to the synchronous
    -- RX FIFO.
    --------------------------------------------------------------------
    signal rx_valid_delayed : STD_LOGIC := '0';


    --------------------------------------------------------------------
    -- Frame error delayed by one clock
    --------------------------------------------------------------------
    signal frame_error_delayed : STD_LOGIC := '0';

begin


    --------------------------------------------------------------------
    -- ================================================================
    -- BAUD GENERATOR
    -- ================================================================
    --------------------------------------------------------------------
    baud_gen_inst : entity work.uart_baud_gen

        port map (
            clk       => clk,
            reset     => reset,
            baud_div  => baud_div,
            baud_tick => baud_tick
        );


    --------------------------------------------------------------------
    -- ================================================================
    -- TX FIFO
    -- ================================================================
    --------------------------------------------------------------------
    tx_fifo_inst : entity work.uart_fifo

        port map (
            clk          => clk,
            reset        => reset,

            wr_en        => tx_write,
            rd_en        => tx_fifo_rd_en,

            din          => tx_data_in,
            dout         => tx_fifo_dout,

            full         => tx_fifo_full,
            empty        => tx_fifo_empty,

            almost_full  => open,
            almost_empty => open,

            level        => open,

            overflow     => open,
            underflow    => open
        );


    --------------------------------------------------------------------
    -- ================================================================
    -- UART TRANSMITTER
    -- ================================================================
    --------------------------------------------------------------------
    uart_tx_inst : entity work.uart_tx

        port map (
            clk       => clk,
            reset     => reset,
            baud_tick => baud_tick,

            tx_data   => uart_tx_data,
            tx_start  => uart_tx_start,

            tx        => tx,
            tx_busy   => uart_tx_busy
        );


    --------------------------------------------------------------------
    -- ================================================================
    -- UART RECEIVER
    -- ================================================================
    --------------------------------------------------------------------
    uart_rx_inst : entity work.uart_rx

        port map (
            clk         => clk,
            reset       => reset,
            baud_tick   => baud_tick,

            rx          => rx,

            rx_data     => uart_rx_data,
            rx_valid    => uart_rx_valid,

            rx_busy     => uart_rx_busy,
            frame_error => uart_frame_error
        );


    --------------------------------------------------------------------
    -- ================================================================
    -- RX VALID DELAY
    --
    -- This is the important fix.
    --
    -- At a clock edge:
    --
    -- uart_rx:
    --     rx_valid changes from 0 -> 1
    --
    -- At that same edge the FIFO still sees the previous 0.
    --
    -- Therefore we register rx_valid and use the registered value
    -- for the FIFO write on the following clock.
    -- ================================================================
    --------------------------------------------------------------------
    rx_valid_delay_process : process(clk)

    begin

        if rising_edge(clk) then

            if reset = '1' then

                rx_valid_delayed <= '0';

                frame_error_delayed <= '0';

            else

                rx_valid_delayed <= uart_rx_valid;

                frame_error_delayed <= uart_frame_error;

            end if;

        end if;

    end process;


    --------------------------------------------------------------------
    -- RX FIFO INPUT
    --------------------------------------------------------------------
    rx_fifo_din <= uart_rx_data;


    --------------------------------------------------------------------
    -- RX FIFO WRITE
    --------------------------------------------------------------------
    rx_fifo_wr_en <= rx_valid_delayed;


    --------------------------------------------------------------------
    -- RX FIFO READ
    --------------------------------------------------------------------
    rx_fifo_rd_en <= rx_read;


    --------------------------------------------------------------------
    -- ================================================================
    -- RX FIFO
    -- ================================================================
    --------------------------------------------------------------------
    rx_fifo_inst : entity work.uart_fifo

        port map (
            clk          => clk,
            reset        => reset,

            wr_en        => rx_fifo_wr_en,
            rd_en        => rx_fifo_rd_en,

            din          => rx_fifo_din,
            dout         => rx_fifo_dout,

            full         => rx_fifo_full,
            empty        => rx_fifo_empty,

            almost_full  => open,
            almost_empty => open,

            level        => open,

            overflow     => open,
            underflow    => open
        );


    --------------------------------------------------------------------
    -- ================================================================
    -- TX FIFO READ CONTROL
    -- ================================================================
    --------------------------------------------------------------------

    tx_fifo_rd_en <= '1'
        when tx_ctrl_state = TX_READ_REQUEST
        else '0';


    --------------------------------------------------------------------
    -- ================================================================
    -- UART TX START
    -- ================================================================
    --------------------------------------------------------------------

    uart_tx_start <= '1'
        when tx_ctrl_state = TX_START
        else '0';


    --------------------------------------------------------------------
    -- ================================================================
    -- TX CONTROL FSM
    -- ================================================================
    --------------------------------------------------------------------
    tx_control_process : process(clk)

    begin

        if rising_edge(clk) then

            if reset = '1' then

                tx_ctrl_state <= TX_IDLE;

                uart_tx_data <= (others => '0');

            else

                case tx_ctrl_state is


                    ----------------------------------------------------
                    -- IDLE
                    ----------------------------------------------------
                    when TX_IDLE =>

                        if tx_fifo_empty = '0' then

                            tx_ctrl_state <= TX_READ_REQUEST;

                        end if;


                    ----------------------------------------------------
                    -- REQUEST TX FIFO READ
                    ----------------------------------------------------
                    when TX_READ_REQUEST =>

                        tx_ctrl_state <= TX_WAIT_DATA;


                    ----------------------------------------------------
                    -- WAIT FOR REGISTERED FIFO OUTPUT
                    ----------------------------------------------------
                    when TX_WAIT_DATA =>

                        uart_tx_data <= tx_fifo_dout;

                        tx_ctrl_state <= TX_START;


                    ----------------------------------------------------
                    -- START UART TX
                    ----------------------------------------------------
                    when TX_START =>

                        tx_ctrl_state <= TX_WAIT_BUSY;


                    ----------------------------------------------------
                    -- WAIT FOR TX BUSY
                    ----------------------------------------------------
                    when TX_WAIT_BUSY =>

                        if uart_tx_busy = '1' then

                            tx_ctrl_state <= TX_WAIT_DONE;

                        end if;


                    ----------------------------------------------------
                    -- WAIT FOR TX COMPLETE
                    ----------------------------------------------------
                    when TX_WAIT_DONE =>

                        if uart_tx_busy = '0' then

                            if tx_fifo_empty = '0' then

                                tx_ctrl_state <= TX_READ_REQUEST;

                            else

                                tx_ctrl_state <= TX_IDLE;

                            end if;

                        end if;


                end case;

            end if;

        end if;

    end process;


    --------------------------------------------------------------------
    -- ================================================================
    -- OUTPUTS
    -- ================================================================
    --------------------------------------------------------------------

    --------------------------------------------------------------------
    -- TX STATUS
    --------------------------------------------------------------------
    tx_full  <= tx_fifo_full;

    tx_empty <= tx_fifo_empty;

    tx_busy  <= uart_tx_busy;


    --------------------------------------------------------------------
    -- RX DATA
    --------------------------------------------------------------------
    rx_data_out <= rx_fifo_dout;


    --------------------------------------------------------------------
    -- RX STATUS
    --------------------------------------------------------------------
    rx_empty <= rx_fifo_empty;

    rx_full  <= rx_fifo_full;


    --------------------------------------------------------------------
    -- RX VALID
    --
    -- This output represents the receiver's valid indication.
    --------------------------------------------------------------------
    rx_valid <= uart_rx_valid;


    --------------------------------------------------------------------
    -- Frame error
    --
    -- Delayed version is exposed so the AXI wrapper can reliably
    -- capture the event.
    --------------------------------------------------------------------
    frame_error <= frame_error_delayed;


end Behavioral;